name: flutter_ug
description: "Ug delegate for flutter_localizations"
version: 0.0.2
homepage: https://github.com/sayiwen/flutter_ug

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: UKIJ Ekran
      fonts:
        - asset: assets/fonts/ukij_ekran.ttf